export const CHARACTER_TYPES = [
  'boy',
  'girl',
  'man',
  'woman',
  'person',
  'dog',
  'cat',
  'bird',
  'other_animal',
  'dragon',
  'elf_fairy_mythical',
  'robot_cyborg',
  'alien_extraterrestrial',
  'other_creature',
  'other',
] as const;

export const CHARACTER_ROLES = [
  'protagonist',
  'antagonist',
  'supporting',
  'mentor',
  'comic_relief',
  'love_interest',
  'sidekick',
  'narrator',
  'other',
] as const;

export const CHARACTER_AGES = [
  'infant',
  'toddler',
  'preschool',
  'school_age',
  'teenage',
  'emerging_adult',
  'seasoned_adult',
  'midlife_mentor',
  'elder',
  'youngling',
  'adult',
  'senior',
] as const;

export const CHARACTER_TRAITS = [
  'adaptable',
  'brave',
  'compassionate',
  'courageous',
  'curious',
  'decisive',
  'empathetic',
  'generous',
  'honest',
  'imaginative',
  'loyal',
  'optimistic',
  'patient',
  'practical',
  'pragmatic',
  'resourceful',
  'self-disciplined',
  'sincere',
  'witty',
  'kind',
  'conscientious',
  'energetic',
  'arrogant',
  'callous',
  'cowardly',
  'cynical',
  'deceitful',
  'impulsive',
  'jealous',
  'lazy',
  'manipulative',
  'moody',
  'reckless',
  'selfish',
  'vengeful',
  'aloof',
  'blunt',
  'cautious',
  'methodical',
] as const;
